#RandomCommand config
#write the list of commands with out the slash and in quotes
#You may make multiple lists of commands
#EX:
#list1:
#- "say this is list one"
#list2:
#- "say this is list two"
#EX:
# you would type restart not /restart
#{name} will be replaced with the player name
#you use it by doing the command /rc <listname> <name>
#you can chose if you want to use %s or not
#if you want to use %
#you add the % by separating the percentage with a :
#the plugin goes top to bottom and in order to guarantee things happen the way you want them to put the items in the order of the percentage you want them to go in
#to guarantee something happens at something that has a %100 chance at the bottom
#EX: 
#commands:
#- "10:say {name} is epic"
#- "50:say {name} is cool"
#- "100:say {name}"
#this will broadcast the name of the player with maybe other stuff
#if you donâ€™t want to use % it will chose a random command and they all have equal chance
use%: true
commands:
- "100:say {name}"
